spring.application.name=notification-service
server.port=8087
meta.whatsapp.access-token=EAASdjGWZAzV4BR9PMQCYBE1utoGNSLnqeOkX930Ovu63dgrL9cvG8EuHPvrDubeMcZBs2ZBuRA5tj5kwTSrW3antdQ8j5E6dWZBNZCT2fwlTnhXtP8Od9ZCk0dqDeyPvldbwKZAWwPsCnGYGkHJv3kZC6N6i00DdqpJ6qQIMNlbVllhvnRPBzlSZBtqghswKgLxGmnNDo2Mb5AIFQsJH7bpc6z2qmA2NeYyy0
meta.whatsapp.phone-number-id=1148326255035152
meta.whatsapp.version=v25.0