spring.application.name=market-stream-service
server.port=8089
market.websocket.url.reconnect-delay=5000
market.websocket.url.heartbeat=30
market.websocket.cache.enabled=true
market.websocket.broker.provider=upstox



upstox.base-url=https://api.upstox.com/

upstox.market-url=https://api.upstox.com/v2
upstox.instrument.url= https://assets.upstox.com/market-quote/instruments/exchange/complete.json.gz
upstox.instrument.url.connect-timeout= 5000
upstox.instrument.url.read-timeout= 30000
upstox.market-feed-url=wss://api.upstox.com/v3/feed/market-data-feed
upstox.default-instruments=NSE_EQ|INE467B01029
#debug=true

#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.context.annotation=DEBUG
#logging.level.org.springframework.beans.factory=INFO
signal.service.base-url=http://localhost:8082
market.stream.auto-start=true
stock.service.url=http://localhost:8081
broker.auth.base-url=http://localhost:9090

market.enabled=true
market.open-time=09:15
market.close-time=15:30
market.timezone=Asia/Kolkata

#####################################################
# ACTUATOR
#####################################################

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.endpoints.web.base-path=/actuator

#####################################################
# PROMETHEUS
#####################################################

management.prometheus.metrics.export.enabled=true

#####################################################
# JVM METRICS
#####################################################

management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true

#####################################################
# APPLICATION INFO
#####################################################

management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.version=1.0.0
info.app.description=AI Trading Platform Microservice