server.port=8080

spring.application.name=api-gateway

# Stock Service
spring.cloud.gateway.routes[0].id=stock-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/stocks/**

# Signal Engine Service
spring.cloud.gateway.routes[1].id=signal-engine-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/signals/**

# Portfolio Service
spring.cloud.gateway.routes[2].id=portfolio-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/portfolio/**