server.port=8080

spring.application.name=api-gateway

# Stock Service
spring.cloud.gateway.routes[0].id=stock-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/stocks/**

# Signal Engine Service
spring.cloud.gateway.routes[1].id=signal-engine-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/signals/**

# Portfolio Service
spring.cloud.gateway.routes[2].id=portfolio-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/portfolio/**

#####################################################
# ACTUATOR
#####################################################

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.endpoints.web.base-path=/actuator

#####################################################
# PROMETHEUS
#####################################################

management.prometheus.metrics.export.enabled=true

#####################################################
# JVM METRICS
#####################################################

management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true

#####################################################
# APPLICATION INFO
#####################################################

management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.version=1.0.0
info.app.description=AI Trading Platform Microservice