spring.application.name=stock-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/ai_trading_platform
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

market.provider=upstox
upstox.client-id=80171a92-43dd-4ba4-91e0-18223eb6fdda
upstox.client-secret=ytsnr8vlr8
upstox.redirect-uri=http://localhost:8081/upstox/callback
upstox.base-url=https://api.upstox.com/v2

upstox.authorization-url=https://api.upstox.com/v2/login/authorization/dialog

upstox.token-url=https://api.upstox.com/v2/login/authorization/token
upstox.analytics-token=eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiI1V0NIUkoiLCJqdGkiOiI2YTRiZGQ1M2JiMTU5OTIxMjA0NWEyMTQiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlhdCI6MTc4MzM1Njc1NSwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxNzgzMzc1MjAwfQ.Yk1jZSX_poQ9OoOtQyhjc74fC-fJBxhCOYIYhvdXo3s
upstox.market-url=https://api.upstox.com/v2
upstox.instrument.url= https://assets.upstox.com/market-quote/instruments/exchange/complete.json.gz
upstox.instrument.url.connect-timeout= 5000
upstox.instrument.url.read-timeout= 30000
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

bootstrap.history.lookback-days=365
bootstrap.history.max-symbols-per-run=500
bootstrap.history.thread-pool-size=10
bootstrap.enabled=false
bootstrap.cron=0 0 8 * * MON-FRI
bootstrap.history.interval=day
bootstrap.history.exchange=NSE
bootstrap.history.segment=NSE_EQ
bootstrap.history.instrument-type=EQ
broker.auth.base-url=http://localhost:9090