spring.application.name=trade-execution-service
server.port=9092
spring.datasource.url=jdbc:mysql://localhost:3306/ai_trading_platform
spring.datasource.username=root
spring.datasource.password=root

balance.margin.service.url=http://localhost:9091
upstox.order-url=https://api-hft.upstox.com/v3/order/place
broker.service.base-url=http://localhost:9090