spring.application.name=newsanalysis-service
spring.ai.openai.api-key=
server.port=8088
spring.ai.openai.chat.options.model=gpt-4o-mini
google.news.rss-url=https://news.google.com/rss/search?q=%s+NSE+India