package com.ram.trading.signal.engine.service;

import com.ram.trading.signal.engine.client.AIServiceClient;
import com.ram.trading.signal.engine.client.NotificationClient;
import com.ram.trading.signal.engine.client.StockServiceClient;
import com.ram.trading.signal.engine.client.interfac.PortfolioClient;
import com.ram.trading.signal.engine.contant.SignalStatus;
import com.ram.trading.signal.engine.contant.SignalType;
import com.ram.trading.signal.engine.dto.*;
import com.ram.trading.signal.engine.dto.ai.portfolio.OpenPositionContextResponse;
import com.ram.trading.signal.engine.dto.market.ExitReason;
import com.ram.trading.signal.engine.dto.market.OpenPosition;
import com.ram.trading.signal.engine.dto.market.Tick;
import com.ram.trading.signal.engine.dto.notification.NotificationChannel;
import com.ram.trading.signal.engine.dto.notification.NotificationRequest;
import com.ram.trading.signal.engine.dto.request.ClosedPositionDto;
import com.ram.trading.signal.engine.dto.request.OpenPositionDashboard;
import com.ram.trading.signal.engine.dto.request.OpportunityDashboard;
import com.ram.trading.signal.engine.dto.response.*;
import com.ram.trading.signal.engine.entity.PaperTrade;
import com.ram.trading.signal.engine.entity.TradingSignalEntity;
import com.ram.trading.signal.engine.exit.ExitDecision;
import com.ram.trading.signal.engine.repo.PaperTradeRepository;
import com.ram.trading.signal.engine.strategy.BasicTradingStrategy;
import com.ram.trading.signal.engine.util.TradeUtil;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import reactor.core.scheduler.Schedulers;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class PaperTradingService {

    private final PaperTradeRepository repository;

    private final AIServiceClient aiServiceClient;

    private final StockServiceClient stockServiceClient;

    private final BasicTradingStrategy basicTradingStrategy;

    private final NotificationClient notificationClient;

    private final SignalService signalService;

    private final PortfolioClient portfolioClient;

    @Value("${trading.capital-per-trade}")
    private double capitalPerTrade;

    public void createTrade(
            TradingSignalEntity signal,
            TechnicalIndicatorResponse indicatorResponse) {

        if (indicatorResponse == null) {
            throw new RuntimeException(
                    "Technical indicators not found for "
                            + signal.getSymbol());
        }

        log.info("Signal Generated = {}", signal.getSignal());

        // Skip HOLD signals immediately
        if (SignalType.HOLD.name().equals(signal.getSignal())) {

            log.info("HOLD Signal. Trade creation skipped.");

            return;
        }

        // Prevent duplicate OPEN trades
        PaperTrade existingTrade =
                repository
                        .findTopBySymbolAndStatusOrderByEntryTimeDesc(
                                signal.getSymbol(),
                                SignalStatus.OPEN)
                        .orElse(null);

        if (existingTrade != null) {

            log.info("======================================");
            log.info("Open Trade Already Exists");
            log.info("Skipping Trade Creation");
            log.info("Symbol : {}", signal.getSymbol());
            log.info("Trade Id : {}", existingTrade.getId());
            log.info("======================================");

            return;
        }

        log.info("Creating New Paper Trade...");

        int quantity =
                (int) (capitalPerTrade
                        / signal.getEntryPrice());

        log.info("quantity ="+quantity);
        if (quantity <= 0) {
            return;
        }
        log.info("Confidence = {}", signal.getConfidence());

        log.info(
                "Creating Trade => Entry={}, Target={}, Stop={}",
                signal.getEntryPrice(),
                signal.getTargetPrice(),
                signal.getStopLoss());

// ======================================================
// BUSINESS VALIDATION
// ======================================================

        if ("BUY".equalsIgnoreCase(signal.getSignal())) {

            if (signal.getTargetPrice() <= signal.getEntryPrice()) {

                log.error(
                        "Invalid Trade Generated by AI. Symbol={}, Signal={}, Entry={}, Target={}, Stop={}",
                        signal.getSymbol(),
                        signal.getSignal(),
                        signal.getEntryPrice(),
                        signal.getTargetPrice(),
                        signal.getStopLoss());

                throw new IllegalStateException(
                        "Invalid BUY Trade : Target Price must be greater than Entry Price.");
            }

            if (signal.getStopLoss() >= signal.getEntryPrice()) {

                log.error(
                        "Invalid Trade Generated by AI. Symbol={}, Signal={}, Entry={}, Target={}, Stop={}",
                        signal.getSymbol(),
                        signal.getSignal(),
                        signal.getEntryPrice(),
                        signal.getTargetPrice(),
                        signal.getStopLoss());

                throw new IllegalStateException(
                        "Invalid BUY Trade : Stop Loss must be less than Entry Price.");
            }

        }
        else if ("SELL".equalsIgnoreCase(signal.getSignal())) {

            if (signal.getTargetPrice() >= signal.getEntryPrice()) {

                log.error(
                        "Invalid Trade Generated by AI. Symbol={}, Signal={}, Entry={}, Target={}, Stop={}",
                        signal.getSymbol(),
                        signal.getSignal(),
                        signal.getEntryPrice(),
                        signal.getTargetPrice(),
                        signal.getStopLoss());

                throw new IllegalStateException(
                        "Invalid SELL Trade : Target Price must be less than Entry Price.");
            }

            if (signal.getStopLoss() <= signal.getEntryPrice()) {

                log.error("Invalid Trade Generated by AI. Symbol={}, Signal={}, Entry={}, Target={}, Stop={}",
                        signal.getSymbol(),
                        signal.getSignal(),
                        signal.getEntryPrice(),
                        signal.getTargetPrice(),
                        signal.getStopLoss());

                throw new IllegalStateException("Invalid SELL Trade : Stop Loss must be greater than Entry Price.");
            }
        }

// ======================================================
// CREATE PAPER TRADE
// ======================================================

        PaperTrade trade =
                PaperTrade.builder()
                        .symbol(signal.getSymbol())
                        .signalId(signal.getId())
                        .signal(signal.getSignal())
                        .entryPrice(round(signal.getEntryPrice()))
                        .quantity(quantity)
                        .investedAmount(
                                quantity *
                                        signal.getEntryPrice())
                        .rsi(indicatorResponse.getRsi14())
                        .ema20(indicatorResponse.getEma20())
                        .ema50(indicatorResponse.getEma50())
                        .macd(indicatorResponse.getMacd())
                        .targetPrice(round(signal.getTargetPrice()))
                        .stopLoss(round(signal.getStopLoss()))
                        .status(SignalStatus.OPEN)
                        .confidence(signal.getConfidence())
                        .entryTime(LocalDateTime.now())
                        .build();
        PaperTrade saved =
                repository.save(trade);

        portfolioClient
                .openPosition(
                        saved.getSymbol(),
                        saved.getQuantity(),
                        saved.getEntryPrice())
                .doOnSuccess(v ->
                        log.info("Portfolio Updated Successfully : {}",
                                saved.getSymbol()))
                .onErrorResume(ex -> {
                    log.error("Portfolio Update Failed", ex);
                    return Mono.empty();
                })
                .subscribe();

        log.info(
                "Saved Trade => target={}, stop={}",
                saved.getTargetPrice(),
                saved.getStopLoss());

        NotificationRequest request =
                NotificationRequest.builder()
                        .channel(NotificationChannel.SLACK)
                        .title("TRADE OPENED")
                        .message(
                                "Symbol: " + signal.getSymbol()
                                        + ", Signal: " + signal.getSignal()
                                        + ", Entry: " + signal.getEntryPrice()
                                        + ", Target: " + signal.getTargetPrice()
                                        + ", StopLoss: " + signal.getStopLoss()
                                        + ", PnL : ₹" + signal.getProfitLoss()
                                        + ", Confidence: "
                                        + signal.getConfidence())
                        .build();

        notificationClient
                .sendNotification(request)
                .doOnError(e ->
                        log.error("Slack Notification Failed", e))
                .subscribe();
    }


    public PaperTrade createPaperTrade(CreatePaperTradeRequest request) {

        PaperTrade trade = PaperTrade.builder()
                .symbol(request.getSymbol())
                .signal(request.getPaperSignal())
                .entryPrice(request.getEntryPrice())
                .quantity(request.getQuantity())
                .investedAmount(request.getEntryPrice() * request.getQuantity())
                .targetPrice(request.getTargetPrice())
                .stopLoss(request.getStopLoss())
                .confidence(request.getConfidence())
                .ema20(request.getEma20())
                .ema50(request.getEma50())
                .macd(request.getMacd())
                .rsi(request.getRsi())
                .status(SignalStatus.OPEN)
                .entryTime(java.time.LocalDateTime.now())
                .build();

        return repository.save(trade);
    }

    private Double round(Double value) {

        if (value == null) {
            return null;
        }

        return BigDecimal.valueOf(value)
                .setScale(2, RoundingMode.HALF_UP)
                .doubleValue();
    }

    public List<PaperTrade> getByStatus(SignalStatus status) {

        return repository.findByStatus(status);
    }

    public List<PaperTrade> getAll() {
        return repository.findAll();
    }

    public Mono<OpenPositionContextResponse> getOpenPositionContext(String symbol) {

        PaperTrade trade = repository
                .findTopBySymbolAndStatusOrderByEntryTimeDesc(
                        symbol,
                        SignalStatus.OPEN)
                .orElse(null);

        if (trade == null) {
            return Mono.just(OpenPositionContextResponse.builder()
                            .positionExists(false)
                            .symbol(symbol)
                            .build());
        }

        return stockServiceClient
                .getStockPrice(symbol)
                .map(stock -> {

                    Double currentPrice = stock.getPrice();

                    Double currentPnL;

                    if ("BUY".equalsIgnoreCase(trade.getSignal())) {

                        currentPnL =
                                (currentPrice - trade.getEntryPrice())
                                        * trade.getQuantity();

                    } else {

                        currentPnL =
                                (trade.getEntryPrice() - currentPrice)
                                        * trade.getQuantity();
                    }

                    Double pnlPercentage =
                            (currentPnL / trade.getInvestedAmount()) * 100;

                    return OpenPositionContextResponse.builder()
                            .positionExists(true)
                            .symbol(trade.getSymbol())
                            .quantity(trade.getQuantity())
                            .entryPrice(trade.getEntryPrice())
                            .currentPrice(currentPrice)
                            .currentPnL(Math.round(currentPnL * 100.0) / 100.0)
                            .pnlPercentage(Math.round(pnlPercentage * 100.0) / 100.0)
                            .stopLoss(trade.getStopLoss())
                            .targetPrice(trade.getTargetPrice())
                            .status(trade.getStatus().name())
                            .signal(trade.getSignal())
                            .build();
                });
    }

    public PaperTradeSummary getSummary() {

        List<PaperTrade> trades =
                repository.findAll();

        long totalTrades =
                trades.size();

        long openPositions =
                trades.stream()
                        .filter(t ->
                                SignalStatus.OPEN
                                        .equals(t.getStatus()))
                        .count();

        long closedPositions =
                totalTrades - openPositions;

        long winningTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() > 0)
                        .count();

        long losingTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() < 0)
                        .count();

        long breakevenTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() == 0)
                        .count();

        double totalInvestment =
                trades.stream()
                        .filter(t ->
                                SignalStatus.OPEN
                                        .equals(t.getStatus()))
                        .mapToDouble(
                                PaperTrade::getInvestedAmount)
                        .sum();

        double totalProfit =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .mapToDouble(
                                PaperTrade::getProfitLoss)
                        .sum();

        double winRate =
                (winningTrades + losingTrades) == 0
                        ? 0
                        : (winningTrades * 100.0)
                        / (winningTrades + losingTrades);

        return PaperTradeSummary.builder()
                .totalTrades(totalTrades)
                .openPositions(openPositions)
                .closedPositions(closedPositions)
                .winningTrades(winningTrades)
                .losingTrades(losingTrades)
                .breakevenTrades(breakevenTrades)
                .totalInvestment(totalInvestment)
                .totalProfit(totalProfit)
                .winRate(Math.round(winRate * 100.0) / 100.0)
                .build();
    }

    public void closeTrade(
            Long signalId,
            Double exitPrice,
            SignalStatus status) {

        PaperTrade trade =
                repository
                        .findBySignalIdAndStatus(
                                signalId,
                                SignalStatus.OPEN)
                        .orElse(null);

        if (trade == null) {
            return;
        }

        trade.setExitPrice(exitPrice);

        double profitLoss;

        if (SignalType.SELL.name()
                .equals(trade.getSignal())) {

            profitLoss =
                    (trade.getEntryPrice()
                            - exitPrice)
                            * trade.getQuantity();

        } else {

            profitLoss =
                    (exitPrice
                            - trade.getEntryPrice())
                            * trade.getQuantity();
        }

        trade.setProfitLoss(profitLoss);

        trade.setStatus(status);

        trade.setExitTime(
                LocalDateTime.now());

        log.info("Closing Trade for signalId="  + signalId);

        log.info( "Trade Found="  + trade.getId());

        log.info( "Profit/Loss=" + profitLoss);

        PaperTrade savedTrade =
                repository.save(trade);

        portfolioClient
                .closePosition(
                        savedTrade.getSymbol(),
                        savedTrade.getQuantity())
                .doOnSuccess(v ->
                        log.info("Portfolio Updated Successfully : {}",
                                savedTrade.getSymbol()))
                .onErrorResume(ex -> {
                    log.error("Portfolio Update Failed", ex);
                    return Mono.empty();
                })
                .subscribe();

        log.info("Trade Closed Successfully");
        log.info("Trade Id : {}", savedTrade.getId());

        NotificationRequest request =
                NotificationRequest.builder()
                        .channel(NotificationChannel.SLACK)
                        .title("TRADE CLOSED")
                        .message(
                                "Symbol: " + trade.getSymbol()
                                        + ", Status: " + status
                                        + ", Entry: "
                                        + trade.getEntryPrice()
                                        + ", Exit: "
                                        + exitPrice
                                        + ", PnL: "
                                        + profitLoss)
                        .build();

        notificationClient
                .sendNotification(request)
                .doOnError(error ->
                        log.error(
                                "Failed to send notification",
                                error))
                .subscribe();
    }

    public List<PaperTrade> getHistory() {
        return repository
                .findAllByOrderByEntryTimeDesc();
    }

    public TradeInsights getInsights() {
        List<PaperTrade> closedTrades =
                repository.findAll()
                        .stream()
                        .filter(trade ->
                                trade.getStatus() != SignalStatus.OPEN)
                        .toList();

        double averageWinningRsi =
                closedTrades.stream()
                        .filter(trade ->
                                trade.getProfitLoss() != null
                                        && trade.getProfitLoss() > 0)
                        .mapToDouble(PaperTrade::getRsi)
                        .average()
                        .orElse(0);

        double averageLosingRsi =
                closedTrades.stream()
                        .filter(trade ->
                                trade.getProfitLoss() != null
                                        && trade.getProfitLoss() < 0)
                        .mapToDouble(PaperTrade::getRsi)
                        .average()
                        .orElse(0);

        double averageWinningMacd =
                closedTrades.stream()
                        .filter(trade ->
                                trade.getProfitLoss() != null
                                        && trade.getProfitLoss() > 0)
                        .mapToDouble(PaperTrade::getMacd)
                        .average()
                        .orElse(0);

        double averageLosingMacd =
                closedTrades.stream()
                        .filter(trade ->
                                trade.getProfitLoss() != null
                                        && trade.getProfitLoss() < 0)
                        .mapToDouble(PaperTrade::getMacd)
                        .average()
                        .orElse(0);

        Integer bestConfidence =
                closedTrades.stream()
                        .filter(trade ->
                                trade.getConfidence() != null)
                        .map(PaperTrade::getConfidence)
                        .max(Integer::compareTo)
                        .orElse(0);

        Integer worstConfidence =
                closedTrades.stream()
                        .filter(trade ->
                                trade.getConfidence() != null)
                        .map(PaperTrade::getConfidence)
                        .min(Integer::compareTo)
                        .orElse(0);

        return TradeInsights.builder()
                .averageWinningRsi(
                        averageWinningRsi)
                .averageLosingRsi(
                        averageLosingRsi)
                .averageWinningMacd(
                        averageWinningMacd)
                .averageLosingMacd(
                        averageLosingMacd)
                .bestConfidence(
                        bestConfidence)
                .worstConfidence(
                        worstConfidence)
                .build();
    }

    public PaperTradeDashboard getDashboard() {

        List<PaperTrade> trades =
                repository.findAll();

        long totalTrades =
                trades.size();

        long openTrades =
                trades.stream()
                        .filter(t ->
                                t.getStatus() ==
                                        SignalStatus.OPEN)
                        .count();

        List<PaperTrade> closedTradesList =
                trades.stream()
                        .filter(t ->
                                t.getStatus() !=
                                        SignalStatus.OPEN)
                        .toList();

        long closedTrades =
                closedTradesList.size();

        long winningTrades =
                closedTradesList.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() > 0)
                        .count();

        long losingTrades =
                closedTradesList.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() < 0)
                        .count();

        long breakevenTrades =
                closedTradesList.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() == 0)
                        .count();

        double totalProfit =
                closedTradesList.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .mapToDouble(
                                PaperTrade::getProfitLoss)
                        .sum();

        double bestTrade =
                closedTradesList.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .mapToDouble(
                                PaperTrade::getProfitLoss)
                        .max()
                        .orElse(0);

        double worstTrade =
                closedTradesList.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .mapToDouble(
                                PaperTrade::getProfitLoss)
                        .min()
                        .orElse(0);

        double winRate =
                closedTrades == 0
                        ? 0
                        : ((double) winningTrades
                        / closedTrades) * 100;

        return PaperTradeDashboard.builder()
                .totalTrades(totalTrades)
                .openTrades(openTrades)
                .closedTrades(closedTrades)
                .winningTrades(winningTrades)
                .losingTrades(losingTrades)
                .breakevenTrades(breakevenTrades)
                .winRate(winRate)
                .totalProfit(totalProfit)
                .bestTrade(bestTrade)
                .worstTrade(worstTrade)
                .build();
    }

    public StrategyReport getStrategyReport() {
        List<PaperTrade> trades =
                repository.findAll()
                        .stream()
                        .filter(t ->
                                t.getStatus() != SignalStatus.OPEN)
                        .toList();

        long totalTrades =
                trades.size();

        long winningTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() > 0)
                        .count();

        long losingTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() < 0)
                        .count();

        double winRate =
                totalTrades == 0
                        ? 0
                        : ((double) winningTrades
                        / totalTrades) * 100;

        double averageConfidence =
                trades.stream()
                        .filter(t ->
                                t.getConfidence() != null)
                        .mapToInt(
                                PaperTrade::getConfidence)
                        .average()
                        .orElse(0);

        double averageWinningConfidence =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() > 0
                                        && t.getConfidence() != null)
                        .mapToInt(
                                PaperTrade::getConfidence)
                        .average()
                        .orElse(0);

        double averageLosingConfidence =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() < 0
                                        && t.getConfidence() != null)
                        .mapToInt(
                                PaperTrade::getConfidence)
                        .average()
                        .orElse(0);

        double averageWinningRsi =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() > 0
                                        && t.getRsi() != null)
                        .mapToDouble(
                                PaperTrade::getRsi)
                        .average()
                        .orElse(0);

        double averageLosingRsi =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() < 0
                                        && t.getRsi() != null)
                        .mapToDouble(
                                PaperTrade::getRsi)
                        .average()
                        .orElse(0);

        long breakevenTrades =  trades.stream().filter(t ->t.getProfitLoss() != null
                                        && t.getProfitLoss() == 0).count();
        return StrategyReport.builder()
                .totalTrades(totalTrades)
                .winningTrades(winningTrades)
                .losingTrades(losingTrades)
                .winRate(winRate)
                .averageConfidence(averageConfidence)
                .averageWinningConfidence(averageWinningConfidence)
                .averageLosingConfidence(averageLosingConfidence)
                .averageWinningRsi(averageWinningRsi)
                .averageLosingRsi(averageLosingRsi)
                .breakevenTrades(breakevenTrades)
                .build();
    }

    public Mono<TradeReviewResponse> reviewTrade(
            Long tradeId) {

        PaperTrade trade =
                repository.findById(tradeId)
                        .orElseThrow();

        if (trade.getExitPrice() == null ||
                trade.getProfitLoss() == null) {

            return Mono.just(
                    TradeReviewResponse.builder()
                            .tradeId(trade.getId())
                            .review(
                                    "Trade is still OPEN. AI review will be available once the trade is completed.")
                            .build());
        }

        TradeReviewRequest request =
                TradeReviewRequest.builder()
                        .tradeId(trade.getId())
                        .symbol(trade.getSymbol())
                        .signal(trade.getSignal())
                        .entryPrice(trade.getEntryPrice())
                        .exitPrice(trade.getExitPrice())
                        .profitLoss(trade.getProfitLoss())
                        .confidence(trade.getConfidence())
                        .rsi(trade.getRsi())
                        .ema20(trade.getEma20())
                        .ema50(trade.getEma50())
                        .macd(trade.getMacd())
                        .build();

        return aiServiceClient.reviewTrade(
                request);
    }

    public Mono<StrategyReviewResponse> strategyReview() {

        List<PaperTrade> trades =
                repository
                        .findTop20ByStatusNotOrderByIdDesc(
                                SignalStatus.OPEN);

        List<TradeReviewRequest> requests =
                trades.stream()
                        .map(trade ->
                                TradeReviewRequest.builder()
                                        .tradeId(trade.getId())
                                        .symbol(trade.getSymbol())
                                        .signal(trade.getSignal())
                                        .entryPrice(trade.getEntryPrice())
                                        .exitPrice(trade.getExitPrice())
                                        .profitLoss(trade.getProfitLoss())
                                        .confidence(trade.getConfidence())
                                        .rsi(trade.getRsi())
                                        .ema20(trade.getEma20())
                                        .ema50(trade.getEma50())
                                        .macd(trade.getMacd())
                                        .build())
                        .toList();
                if (requests.isEmpty()) {
                    return Mono.just(
                            StrategyReviewResponse.builder()
                                    .totalTrades(0)
                                    .winningTrades(0)
                                    .losingTrades(0)
                                    .review("No completed trades available for strategy review.")
                                    .build());
                }
        return aiServiceClient
                .reviewStrategy(requests);
    }

    public TradeAnalyticsResponse getAnalytics() {

        List<PaperTrade> completedTrades =
                repository.findAll()
                        .stream()
                        .filter(trade ->
                                trade.getProfitLoss() != null)
                        .toList();

        long totalTrades = completedTrades.size();

        long winningTrades =
                completedTrades.stream()
                        .filter(t -> t.getProfitLoss() > 0)
                        .count();

        long losingTrades =
                completedTrades.stream()
                        .filter(t -> t.getProfitLoss() < 0)
                        .count();

        double totalProfit =
                completedTrades.stream()
                        .mapToDouble(PaperTrade::getProfitLoss)
                        .sum();

        double winRate =
                totalTrades == 0
                        ? 0
                        : (winningTrades * 100.0) / totalTrades;

        long breakevenTrades =
                completedTrades.stream()
                        .filter(t -> t.getProfitLoss() == 0)
                        .count();

        double averageLoss =
                completedTrades.stream()
                        .filter(t -> t.getProfitLoss() != null)
                        .filter(t -> t.getProfitLoss() < 0)
                        .mapToDouble(PaperTrade::getProfitLoss)
                        .average()
                        .orElse(0.0);

        double bestTrade =
                completedTrades.stream()
                        .filter(t -> t.getProfitLoss() != null)
                        .mapToDouble(PaperTrade::getProfitLoss)
                        .max()
                        .orElse(0.0);

        double worstTrade =
                completedTrades.stream()
                        .filter(t -> t.getProfitLoss() != null)
                        .mapToDouble(PaperTrade::getProfitLoss)
                        .min()
                        .orElse(0.0);

        double averageProfit =
                completedTrades.stream()
                        .filter(t -> t.getProfitLoss() != null)
                        .filter(t -> t.getProfitLoss() > 0)
                        .mapToDouble(PaperTrade::getProfitLoss)
                        .average()
                        .orElse(0.0);

        return TradeAnalyticsResponse.builder()
                .totalTrades(totalTrades)
                .winningTrades(winningTrades)
                .losingTrades(losingTrades)
                .breakevenTrades(breakevenTrades)
                .winRate(winRate)
                .totalProfit(totalProfit)
                .averageProfit(averageProfit)
                .averageLoss(averageLoss)
                .bestTrade(bestTrade)
                .worstTrade(worstTrade)
                .build();
    }

    public Mono<PositionSizingResponse> getPositionSize(String symbol, Double capital) {

        return stockServiceClient
                .getStockPrice(symbol)
                .flatMap(basicTradingStrategy::generateSignal)
                .map(signal -> {

                    double allocationPercentage =
                            TradeUtil.getAllocationPercentage(
                                    signal.getConfidence());

                    double investment =
                            capital * allocationPercentage;

                    int quantity =
                            (int) (investment
                                    / signal.getEntryPrice());

                    double riskPerShare;

                    if ("BUY".equals(signal.getSignal())) {

                        riskPerShare =
                                signal.getEntryPrice()
                                        - signal.getStopLoss();

                    } else {

                        riskPerShare =
                                signal.getStopLoss()
                                        - signal.getEntryPrice();
                    }

                    return PositionSizingResponse
                            .builder()
                            .symbol(signal.getSymbol())
                            .capital(capital)
                            .confidence(signal.getConfidence())
                            .recommendedInvestment(TradeUtil.round(investment))
                            .recommendedQuantity(quantity)
                            .riskPerShare(TradeUtil.round(riskPerShare))
                            .totalRisk(TradeUtil.round(quantity * riskPerShare))
                            .build();
                });
    }

    public DailyPnLResponse getDailyPnL() {

        LocalDate today =
                LocalDate.now();

        List<PaperTrade> trades =
                repository.findAll()
                        .stream()
                        .filter(t ->
                                t.getExitTime() != null)
                        .filter(t ->
                                t.getExitTime()
                                        .toLocalDate()
                                        .equals(today))
                        .toList();

        double todayProfit =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .mapToDouble(
                                PaperTrade::getProfitLoss)
                        .sum();

        long winningTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .filter(t ->
                                t.getProfitLoss() > 0)
                        .count();

        long losingTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .filter(t ->
                                t.getProfitLoss() < 0)
                        .count();

        long breakevenTrades =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null)
                        .filter(t ->
                                t.getProfitLoss() == 0)
                        .count();

        return DailyPnLResponse.builder()
                .todayProfit(todayProfit)
                .totalTrades(
                        (long) trades.size())
                .winningTrades(winningTrades)
                .losingTrades(losingTrades)
                .breakevenTrades(
                        breakevenTrades)
                .build();
    }

    public TradingDashboardResponse getPnLDashboard() {

        TradeAnalyticsResponse analytics =
                getAnalytics();

        DailyPnLResponse dailyPnL =
                getDailyPnL();

        long openTrades = repository.countByStatus(SignalStatus.OPEN);

        return TradingDashboardResponse
                .builder()
                .totalTrades(
                        analytics.getTotalTrades())
                .winningTrades(
                        analytics.getWinningTrades())
                .losingTrades(
                        analytics.getLosingTrades())
                .breakevenTrades(
                        analytics.getBreakevenTrades())
                .winRate(
                        analytics.getWinRate())
                .totalProfit(
                        analytics.getTotalProfit())
                .todayProfit(
                        dailyPnL.getTodayProfit())
                .averageProfit(
                        analytics.getAverageProfit())
                .averageLoss(
                        analytics.getAverageLoss())
                .bestTrade(
                        analytics.getBestTrade())
                .worstTrade(
                        analytics.getWorstTrade())
                .openTrades(
                        openTrades)
                .build();
    }

    public Mono<OpportunityDashboardResponse> getBestOpportunities(
            Double capital) {

        return signalService
                .getTopOpportunities()
                .take(3)

                .flatMap(opportunity ->

                        getPositionSize(
                                opportunity.getSymbol(),
                                capital)

                                .map(position -> {

                                    double reward =
                                            Math.abs(
                                                    opportunity.getTargetPrice()
                                                            - opportunity.getEntryPrice());

                                    double risk =
                                            Math.abs(
                                                    opportunity.getEntryPrice()
                                                            - opportunity.getStopLoss());

                                    double riskRewardRatio =
                                            risk == 0
                                                    ? 0
                                                    : Math.round((reward / risk) * 100.0) / 100.0;

                                       return OpportunityDashboard
                                                .builder()
                                                .symbol(opportunity.getSymbol())
                                                .signal(opportunity.getSignal())
                                                .confidence(opportunity.getConfidence())
                                                .tradeScore(opportunity.getScore())
                                                .targetPrice(opportunity.getTargetPrice())
                                                .stopLoss(opportunity.getStopLoss())
                                                .entryPrice(opportunity.getEntryPrice())
                                                .sentiment(opportunity.getSentiment())
                                                .sentimentScore(opportunity.getSentimentScore())
                                                .technicalReason(opportunity.getTechnicalReason())
                                                .sentimentReason(opportunity.getSentimentReason())
                                                .recommendation(opportunity.getRecommendation())
                                                .recommendedInvestment(position.getRecommendedInvestment())
                                                .recommendedQuantity(position.getRecommendedQuantity())
                                                .riskPerShare(position.getRiskPerShare())
                                                .totalRisk(position.getTotalRisk())
                                                .riskRewardRatio(riskRewardRatio)
                                                .build();}))
                                                .collectList()
                                        .map(list -> {

                                            for (int i = 0; i < list.size(); i++) {
                                                list.get(i).setRank(i + 1);
                                            }

                                            double recommendedCapital =
                                                    list.stream()
                                                            .mapToDouble(
                                                                    OpportunityDashboard::getRecommendedInvestment)
                                                            .sum();

                                            return OpportunityDashboardResponse
                                                    .builder()
                                                    .capital(capital)
                                                    .recommendedCapital(recommendedCapital)
                                                    .remainingCapital(capital - recommendedCapital)
                                                    .opportunityCount(list.size())
                                                    .opportunities(list)
                                                    .build();
                                        });
    }

    public AnalyticsMetricsResponse getAdvancedMetrics() {

        List<PaperTrade> trades =
                repository.findAll()
                        .stream()
                        .filter(t -> t.getProfitLoss() != null)
                        .toList();

        if (trades.isEmpty()) {

            return AnalyticsMetricsResponse.builder()
                    .profitFactor(0)
                    .expectancy(0)
                    .maxDrawdown(0)
                    .consecutiveWins(0)
                    .consecutiveLosses(0)
                    .build();
        }

        double grossProfit =
                trades.stream()
                        .filter(t -> t.getProfitLoss() > 0)
                        .mapToDouble(PaperTrade::getProfitLoss)
                        .sum();

        double grossLoss =
                Math.abs(
                        trades.stream()
                                .filter(t -> t.getProfitLoss() < 0)
                                .mapToDouble(PaperTrade::getProfitLoss)
                                .sum());

        double profitFactor =
                grossLoss == 0
                        ? grossProfit
                        : grossProfit / grossLoss;

        long winningTrades =
                trades.stream()
                        .filter(t -> t.getProfitLoss() > 0)
                        .count();

        long losingTrades =
                trades.stream()
                        .filter(t -> t.getProfitLoss() < 0)
                        .count();

        double avgWin =
                trades.stream()
                        .filter(t -> t.getProfitLoss() > 0)
                        .mapToDouble(PaperTrade::getProfitLoss)
                        .average()
                        .orElse(0);

        double avgLoss =
                Math.abs(
                        trades.stream()
                                .filter(t -> t.getProfitLoss() < 0)
                                .mapToDouble(PaperTrade::getProfitLoss)
                                .average()
                                .orElse(0));

        double totalTrades =
                winningTrades + losingTrades;

        double winRate =
                totalTrades == 0
                        ? 0
                        : winningTrades / totalTrades;

        double lossRate =
                totalTrades == 0
                        ? 0
                        : losingTrades / totalTrades;

        double expectancy =
                (winRate * avgWin)
                        - (lossRate * avgLoss);

        double maxDrawdown =
                TradeUtil.calculateMaxDrawdown(trades);

        long consecutiveWins =
                TradeUtil.calculateConsecutiveWins(trades);

        long consecutiveLosses =
                TradeUtil.calculateConsecutiveLosses(trades);

        return AnalyticsMetricsResponse.builder()
                .profitFactor(TradeUtil.round(profitFactor))
                .expectancy(TradeUtil.round(expectancy))
                .maxDrawdown(TradeUtil.round(maxDrawdown))
                .consecutiveWins(consecutiveWins)
                .consecutiveLosses(consecutiveLosses)
                .build();
    }

    public PerformanceAnalytics getPerformanceAnalytics() {

        List<PaperTrade> trades =
                repository.findAll();

        int totalTrades = trades.size();

        int openTrades =
                (int) trades.stream()
                        .filter(t ->
                                t.getStatus() == SignalStatus.OPEN)
                        .count();

        int winningTrades =
                (int) trades.stream()
                        .filter(t ->
                                t.getStatus() == SignalStatus.TARGET_HIT)
                        .count();

        int losingTrades =
                (int) trades.stream()
                        .filter(t ->
                                t.getStatus() == SignalStatus.STOP_LOSS_HIT)
                        .count();

        double totalProfit =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() > 0)
                        .mapToDouble(
                                PaperTrade::getProfitLoss)
                        .sum();

        double totalLoss =
                trades.stream()
                        .filter(t ->
                                t.getProfitLoss() != null
                                        && t.getProfitLoss() < 0)
                        .mapToDouble(
                                PaperTrade::getProfitLoss)
                        .sum();

        double netProfit =
                totalProfit + totalLoss;

        double winRate =
                (winningTrades + losingTrades) == 0
                        ? 0
                        : ((double) winningTrades
                        / (winningTrades + losingTrades))
                        * 100;

        double averageProfit =
                winningTrades == 0
                        ? 0
                        : totalProfit / winningTrades;

        double averageLoss =
                losingTrades == 0
                        ? 0
                        : Math.abs(totalLoss)
                        / losingTrades;

        double profitFactor =
                totalLoss == 0
                        ? totalProfit
                        : totalProfit
                        / Math.abs(totalLoss);

        return PerformanceAnalytics
                .builder()
                .totalTrades(totalTrades)
                .openTrades(openTrades)
                .winningTrades(winningTrades)
                .losingTrades(losingTrades)
                .winRate(
                        Math.round(winRate * 100.0)
                                / 100.0)
                .totalProfit(totalProfit)
                .totalLoss(totalLoss)
                .netProfit(netProfit)
                .averageProfit(averageProfit)
                .averageLoss(averageLoss)
                .profitFactor(
                        Math.round(profitFactor * 100.0)
                                / 100.0)
                .build();
    }

    public Mono<OpenPositionDashboard> getOpenPositions() {

        return Flux.fromIterable(
                        repository.findByStatus(
                                SignalStatus.OPEN))

                .flatMap(trade ->

                        stockServiceClient
                                .getStockPrice(
                                        trade.getSymbol())

                                .map(stock -> {

                                    Double currentPrice =
                                            stock.getPrice();

                                    double progress = 0.0;

                                    if ("BUY".equalsIgnoreCase(trade.getSignal())) {

                                        progress =
                                                ((currentPrice - trade.getEntryPrice())
                                                        /
                                                        (trade.getTargetPrice() - trade.getEntryPrice()))
                                                        * 100;

                                    } else if ("SELL".equalsIgnoreCase(trade.getSignal())) {

                                        progress =
                                                ((trade.getEntryPrice() - currentPrice)
                                                        /
                                                        (trade.getEntryPrice() - trade.getTargetPrice()))
                                                        * 100;
                                    }

                                    if (!Double.isFinite(progress)) {
                                        progress = 0.0;
                                    }

                                    progress = Math.max(0.0, progress);

                                    progress =
                                            Math.round(progress * 100.0)
                                                    / 100.0;

                                    Double currentValue =
                                            currentPrice
                                                    * trade.getQuantity();

                                    Double pnl =
                                            currentValue
                                                    - trade.getInvestedAmount();

                                    Double pnlPercent =
                                            (pnl
                                                    / trade.getInvestedAmount())
                                                    * 100;


                                    return OpenPositionResponse
                                            .builder()
                                            .tradeId(trade.getId())
                                            .symbol(trade.getSymbol())
                                            .signal(trade.getSignal())
                                            .entryPrice(trade.getEntryPrice())
                                            .currentPrice(currentPrice)
                                            .targetPrice(trade.getTargetPrice())
                                            .stopLoss(trade.getStopLoss())
                                            .quantity(trade.getQuantity())
                                            .targetProgress(progress)
                                            .investedAmount(
                                                    trade.getInvestedAmount())
                                            .currentValue(currentValue)
                                            .currentPnL(pnl)
                                            .pnlPercentage(
                                                    Math.round(
                                                            pnlPercent * 100.0)
                                                            / 100.0)
                                            .status(
                                                    trade.getStatus().name())
                                            .build();
                                }))

                .collectList()


                .map(positions -> {

                    double totalInvestment =
                            positions.stream()
                                    .mapToDouble(
                                            OpenPositionResponse::getInvestedAmount)
                                    .sum();

                    double currentValue =
                            positions.stream()
                                    .mapToDouble(
                                            OpenPositionResponse::getCurrentValue)
                                    .sum();

                    double currentPnL =
                            currentValue
                                    - totalInvestment;

                    positions.forEach(position -> {

                        double allocation =
                                (position.getInvestedAmount()
                                        / totalInvestment) * 100;

                        position.setPortfolioAllocation(
                                Math.round(allocation * 100.0) / 100.0);
                    });

                    OpenPositionResponse best =
                            positions.stream()
                                    .max(
                                            Comparator.comparing(
                                                    OpenPositionResponse::getCurrentPnL))
                                    .orElse(null);

                    OpenPositionResponse worst =
                            positions.stream()
                                    .min(
                                            Comparator.comparing(
                                                    OpenPositionResponse::getCurrentPnL))
                                    .orElse(null);

                    return OpenPositionDashboard
                            .builder()
                            .openTrades(
                                    positions.size())
                            .totalInvestment(
                                    totalInvestment)
                            .currentValue(
                                    currentValue)
                            .currentPnL(
                                    currentPnL)
                            .positions(
                                    positions)
                            .bestPosition(best != null ? best.getSymbol()
                                            : null)

                            .bestPnL(
                                    best != null
                                            ? best.getCurrentPnL()
                                            : 0)

                            .worstPosition(
                                    worst != null
                                            ? worst.getSymbol()
                                            : null)

                            .worstPnL(
                                    worst != null
                                            ? worst.getCurrentPnL()
                                            : 0)

                            .availableCapital(
                                    100000 - totalInvestment)
                            .build();
                });
    }

    public Mono<Void> closeTrade(
            PaperTrade trade,
            ExitDecision decision,
            Tick tick) {

        log.info("==========================================");
        log.info("CLOSING PAPER TRADE");
        log.info("Symbol : {}", trade.getSymbol());
        log.info("Entry Price : {}", trade.getEntryPrice());
        log.info("Exit Price : {}", tick.getLastTradedPrice());

        if (decision.getReason() == ExitReason.TARGET) {

            trade.setStatus(
                    SignalStatus.TARGET_HIT);

        }
        else if (decision.getReason() == ExitReason.STOP_LOSS) {

            trade.setStatus(
                    SignalStatus.STOP_LOSS_HIT);

        }
        else {

            trade.setStatus(
                    SignalStatus.CLOSED);

        }

        trade.setExitPrice(tick.getLastTradedPrice());

        trade.setExitTime(LocalDateTime.now());

        Double pnl = calculatePnL(trade);

        trade.setProfitLoss(pnl);

        log.info("Profit/Loss : {}", pnl);

        return Mono.fromCallable(() -> {

                    PaperTrade savedTrade = repository.save(trade);

                    log.info("Trade Closed Successfully");
                    log.info("Trade Id : {}", savedTrade.getId());

                    return savedTrade;

                })
                .subscribeOn(Schedulers.boundedElastic())
                .then();
    }

    private Double calculatePnL(PaperTrade trade) {

        if ("SELL".equalsIgnoreCase(trade.getSignal())) {

            return (trade.getEntryPrice()
                    - trade.getExitPrice())
                    * trade.getQuantity();
        }

        return (trade.getExitPrice()
                - trade.getEntryPrice())
                * trade.getQuantity();
    }



    public ClosedPositionResponse getClosedPositions() {

        List<PaperTrade> trades = repository.findByStatusIn(
                        List.of(
                                SignalStatus.TARGET_HIT,
                                SignalStatus.STOP_LOSS_HIT
                        ))
                .stream()
                .sorted(Comparator.comparing(PaperTrade::getExitTime).reversed())
                .toList();

        List<ClosedPositionDto> positions = trades.stream()
                .map(this::mapToClosedPosition)
                .toList();

        int totalTrades = trades.size();

        int winningTrades = (int) trades.stream()
                .filter(t -> t.getProfitLoss() != null && t.getProfitLoss() > 0)
                .count();

        int losingTrades = (int) trades.stream()
                .filter(t -> t.getProfitLoss() != null && t.getProfitLoss() < 0)
                .count();

        double totalProfit = trades.stream()
                .filter(t -> t.getProfitLoss() != null && t.getProfitLoss() > 0)
                .mapToDouble(PaperTrade::getProfitLoss)
                .sum();

        double totalLoss = trades.stream()
                .filter(t -> t.getProfitLoss() != null && t.getProfitLoss() < 0)
                .mapToDouble(PaperTrade::getProfitLoss)
                .sum();

        double netProfit = trades.stream()
                .filter(t -> t.getProfitLoss() != null)
                .mapToDouble(PaperTrade::getProfitLoss)
                .sum();

        double winRate = totalTrades == 0
                ? 0.0
                : ((double) winningTrades / totalTrades) * 100;

        double averageProfit = winningTrades == 0
                ? 0.0
                : totalProfit / winningTrades;

        double averageLoss = losingTrades == 0
                ? 0.0
                : Math.abs(totalLoss) / losingTrades;

        double profitFactor = totalLoss == 0
                ? totalProfit
                : totalProfit / Math.abs(totalLoss);

        return ClosedPositionResponse.builder()
                .totalTrades(totalTrades)
                .winningTrades(winningTrades)
                .losingTrades(losingTrades)
                .winRate(winRate)
                .totalProfit(totalProfit)
                .totalLoss(Math.abs(totalLoss))
                .netProfit(netProfit)
                .averageProfit(averageProfit)
                .averageLoss(averageLoss)
                .profitFactor(profitFactor)
                .positions(positions)
                .build();
    }

    private ClosedPositionDto mapToClosedPosition(PaperTrade trade) {

        return ClosedPositionDto.builder()
                .tradeId(trade.getId())
                .signalId(trade.getSignalId())
                .symbol(trade.getSymbol())
                .signal(trade.getSignal())
                .entryPrice(trade.getEntryPrice())
                .exitPrice(trade.getExitPrice())
                .quantity(trade.getQuantity())
                .investedAmount(trade.getInvestedAmount())
                .profitLoss(trade.getProfitLoss())
                .targetPrice(trade.getTargetPrice())
                .stopLoss(trade.getStopLoss())
                .confidence(trade.getConfidence())
                .status(trade.getStatus().name())
                .entryTime(trade.getEntryTime())
                .exitTime(trade.getExitTime())
                .closedAt(trade.getExitTime())
                .build();
    }

}