spring.application.name=portfolio-service
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/ai_trading_platform
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

#####################################################
# ACTUATOR
#####################################################

management.endpoints.web.exposure.include=health,info,metrics,prometheus

management.endpoint.health.show-details=always

management.endpoints.web.base-path=/actuator

#####################################################
# PROMETHEUS
#####################################################

management.prometheus.metrics.export.enabled=true

#####################################################
# JVM METRICS
#####################################################

management.metrics.enable.jvm=true
management.metrics.enable.process=true
management.metrics.enable.system=true

#####################################################
# APPLICATION INFO
#####################################################

management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.version=1.0.0
info.app.description=AI Trading Platform Microservice